#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Install docker compose from the binary distribution
# See https://docs.docker.com/compose/install/#alternative-install-options

curl -sL https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose > /dev/null 2>&1
chmod +x /usr/local/bin/docker-compose

# Install bash completion file

curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose > /dev/null 2>&1
