#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Install docker compose from pip

pip install --system --disable-pip-version-check docker-compose > /dev/null

# Install bash completion file

curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose > /dev/null 2>&1
