#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Launch the Portainer GUI for managing containers
# See https://github.com/portainer/portainer

systemctl enable docker-compose@portainer
systemctl start docker-compose@portainer

echo "You can access Portainer at http://localhost:9000"
