#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Install latest docker version via the get.docker.com script

apt-get install -y curl > /dev/null
curl -sL https://get.docker.com | bash > /dev/null 2>&1
adduser vagrant docker > /dev/null 2>&1
