#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

export DEBIAN_FRONTEND=noninteractive

# Install python2 with pip and virtualenv modules

apt-get install -y python python-pip python-virtualenv > /dev/null
